### ISSUE TITLE
TODO: indexer script

### ISSUE THREAD

**Issue by brandonjpierce** [gohypergiant/standard-toolkit#39]
- Swap to `@swc/core` instead of `@babel/parser`
- Update indexer script 
- Optionally refactor everything into `scripts/indexer-v2.mjs` file

**Comment by belsrc** [comment]
I would potentially put this, as it is, deeper in the backlog. Given recent conversations. Or we can update once those discussions have been ironed out more.

**Comment by belsrc** [comment]
See also #67

**Comment by belsrc** [comment]
Closing, superseded by #67

**Comment by belsrc** [comment]
Closing, superseded by #67
