### ISSUE TITLE
More contributing guides / how-tos

### ISSUE THREAD

**Issue by brandonjpierce** [gohypergiant/standard-toolkit#47]
- Changesets how to
- What happens pre/post merge etc
- Approval process and pipeline checks

**Comment by brandonjpierce** [comment]
I am somewhat indifferent to where this is added. It may be better suited for a `documentation/*` file since the root `CONTRIBUTING.md` file is aimed more at a generalized contributing guide for the community at large. But I could definitely see an argument both ways as far as where the content lands.

**Comment by brandonjpierce** [comment]
Perhaps add in content for how we manage our kanban board, labels, etc?

**Comment by belsrc** [comment]
@brandonjpierce would probably be good to have general guidelines (though need actions to enforce as well) on things like commits messages and PRs being conventioncommit-like?

**Comment by brandonjpierce** [comment]
@belsrc agreed! @kalisjoshua since you are tackling this now, perhaps some notes on our commit style: https://www.conventionalcommits.org/en/v1.0.0/ and titles following a similar semantic

**Comment by kalisjoshua** [comment]
> [@belsrc](https://github.com/belsrc) agreed! [@kalisjoshua](https://github.com/kalisjoshua) since you are tackling this now, perhaps some notes on our commit style: https://www.conventionalcommits.org/en/v1.0.0/ and titles following a similar semantic

An area I will need to get better in myself.
