### ISSUE TITLE
Codeowners file(s)

### ISSUE THREAD

**Issue by brandonjpierce** [gohypergiant/standard-toolkit#5]
Can likely start with a root one with all maintainer sans Tim listed. We can refine over time.

Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by belsrc** [comment]
Theres a few that are pretty cut and dry that we can start out with. Ray on DS and me/you on some of the lower level.
